//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfrig.Integration.Test.IntegrationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestContractBase", Namespace="http://schemas.datacontract.org/2004/07/Marfrig.Framework.Patterns.RequestRespons" +
        "e")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Marfrig.Integration.Test.IntegrationService.OrderTrackingRequest))]
    public partial class RequestContractBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marfrig.Integration.Test.IntegrationService.Credentials CredentialsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marfrig.Integration.Test.IntegrationService.Credentials Credentials {
            get {
                return this.CredentialsField;
            }
            set {
                if ((object.ReferenceEquals(this.CredentialsField, value) != true)) {
                    this.CredentialsField = value;
                    this.RaisePropertyChanged("Credentials");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credentials", Namespace="http://schemas.datacontract.org/2004/07/Marfrig.Framework.Patterns.RequestRespons" +
        "e")]
    [System.SerializableAttribute()]
    public partial class Credentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AuthTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequesterIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marfrig.Integration.Test.IntegrationService.RequesterSystem RequesterSystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marfrig.Integration.Test.IntegrationService.RequesterUser RequesterUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AuthToken {
            get {
                return this.AuthTokenField;
            }
            set {
                if ((this.AuthTokenField.Equals(value) != true)) {
                    this.AuthTokenField = value;
                    this.RaisePropertyChanged("AuthToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequesterIP {
            get {
                return this.RequesterIPField;
            }
            set {
                if ((object.ReferenceEquals(this.RequesterIPField, value) != true)) {
                    this.RequesterIPField = value;
                    this.RaisePropertyChanged("RequesterIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marfrig.Integration.Test.IntegrationService.RequesterSystem RequesterSystem {
            get {
                return this.RequesterSystemField;
            }
            set {
                if ((object.ReferenceEquals(this.RequesterSystemField, value) != true)) {
                    this.RequesterSystemField = value;
                    this.RaisePropertyChanged("RequesterSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marfrig.Integration.Test.IntegrationService.RequesterUser RequesterUser {
            get {
                return this.RequesterUserField;
            }
            set {
                if ((object.ReferenceEquals(this.RequesterUserField, value) != true)) {
                    this.RequesterUserField = value;
                    this.RaisePropertyChanged("RequesterUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderTrackingRequest", Namespace="http://schemas.datacontract.org/2004/07/Marfrig.Integration.ServiceInterfaces.Mes" +
        "sageContracts")]
    [System.SerializableAttribute()]
    public partial class OrderTrackingRequest : Marfrig.Integration.Test.IntegrationService.RequestContractBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marfrig.Integration.Test.IntegrationService.OrderTracking[] TrackingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marfrig.Integration.Test.IntegrationService.OrderTracking[] Trackings {
            get {
                return this.TrackingsField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackingsField, value) != true)) {
                    this.TrackingsField = value;
                    this.RaisePropertyChanged("Trackings");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderTracking", Namespace="http://schemas.datacontract.org/2004/07/Marfrig.Order.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class OrderTracking : Marfrig.Integration.Test.IntegrationService.BusinessEntityBaseOfOrderTrackingW5JXwJlJ {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequesterSystem", Namespace="http://schemas.datacontract.org/2004/07/Marfrig.Framework.Patterns.RequestRespons" +
        "e")]
    [System.SerializableAttribute()]
    public partial class RequesterSystem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequesterUser", Namespace="http://schemas.datacontract.org/2004/07/Marfrig.Framework.Patterns.RequestRespons" +
        "e")]
    [System.SerializableAttribute()]
    public partial class RequesterUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessEntityBase", Namespace="http://schemas.datacontract.org/2004/07/Marfrig.Framework.BusinessEntities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Marfrig.Integration.Test.IntegrationService.BusinessEntityBaseOfOrderTrackingW5JXwJlJ))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Marfrig.Integration.Test.IntegrationService.OrderTracking))]
    public partial class BusinessEntityBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.Dictionary<object, object> extendedPropertiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<object, object> extendedProperties {
            get {
                return this.extendedPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.extendedPropertiesField, value) != true)) {
                    this.extendedPropertiesField = value;
                    this.RaisePropertyChanged("extendedProperties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessEntityBaseOfOrderTrackingW5JXwJlJ", Namespace="http://schemas.datacontract.org/2004/07/Marfrig.Framework.BusinessEntities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Marfrig.Integration.Test.IntegrationService.OrderTracking))]
    public partial class BusinessEntityBaseOfOrderTrackingW5JXwJlJ : Marfrig.Integration.Test.IntegrationService.BusinessEntityBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultBase", Namespace="http://schemas.datacontract.org/2004/07/Marfrig.Framework.Patterns.RequestRespons" +
        "e")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Marfrig.Integration.Test.IntegrationService.ValidationExceptionFault))]
    public partial class FaultBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationExceptionFault", Namespace="http://schemas.datacontract.org/2004/07/Marfrig.Integration.ServiceInterfaces.Fau" +
        "ltContracts")]
    [System.SerializableAttribute()]
    public partial class ValidationExceptionFault : Marfrig.Integration.Test.IntegrationService.FaultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] validationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] validations {
            get {
                return this.validationsField;
            }
            set {
                if ((object.ReferenceEquals(this.validationsField, value) != true)) {
                    this.validationsField = value;
                    this.RaisePropertyChanged("validations");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseContractBase", Namespace="http://schemas.datacontract.org/2004/07/Marfrig.Framework.Patterns.RequestRespons" +
        "e")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Marfrig.Integration.Test.IntegrationService.OrderTrackingResponse))]
    public partial class ResponseContractBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderTrackingResponse", Namespace="http://schemas.datacontract.org/2004/07/Marfrig.Integration.ServiceInterfaces.Mes" +
        "sageContracts")]
    [System.SerializableAttribute()]
    public partial class OrderTrackingResponse : Marfrig.Integration.Test.IntegrationService.ResponseContractBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Marfrig.Integration.ServiceInterfaces", ConfigurationName="IntegrationService.IntegrationService")]
    public interface IntegrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Marfrig.Integration.ServiceInterfaces.ReceiveOrderTracking", ReplyAction="urn:Marfrig.Integration.ServiceInterfaces/IntegrationService/ReceiveOrderTracking" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(Marfrig.Integration.Test.IntegrationService.ValidationExceptionFault), Action="urn:Marfrig.Integration.ServiceInterfaces/IntegrationService/ReceiveOrderTracking" +
            "ValidationExceptionFaultFault", Name="ValidationExceptionFault", Namespace="http://schemas.datacontract.org/2004/07/Marfrig.Integration.ServiceInterfaces.Fau" +
            "ltContracts")]
        Marfrig.Integration.Test.IntegrationService.OrderTrackingResponse ReceiveOrderTracking(Marfrig.Integration.Test.IntegrationService.OrderTrackingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Marfrig.Integration.ServiceInterfaces.ReceiveOrderTracking", ReplyAction="urn:Marfrig.Integration.ServiceInterfaces/IntegrationService/ReceiveOrderTracking" +
            "Response")]
        System.Threading.Tasks.Task<Marfrig.Integration.Test.IntegrationService.OrderTrackingResponse> ReceiveOrderTrackingAsync(Marfrig.Integration.Test.IntegrationService.OrderTrackingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Marfrig.Integration.ServiceInterfaces/IntegrationService/TestMethod", ReplyAction="urn:Marfrig.Integration.ServiceInterfaces/IntegrationService/TestMethodResponse")]
        string TestMethod();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Marfrig.Integration.ServiceInterfaces/IntegrationService/TestMethod", ReplyAction="urn:Marfrig.Integration.ServiceInterfaces/IntegrationService/TestMethodResponse")]
        System.Threading.Tasks.Task<string> TestMethodAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IntegrationServiceChannel : Marfrig.Integration.Test.IntegrationService.IntegrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegrationServiceClient : System.ServiceModel.ClientBase<Marfrig.Integration.Test.IntegrationService.IntegrationService>, Marfrig.Integration.Test.IntegrationService.IntegrationService {
        
        public IntegrationServiceClient() {
        }
        
        public IntegrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Marfrig.Integration.Test.IntegrationService.OrderTrackingResponse ReceiveOrderTracking(Marfrig.Integration.Test.IntegrationService.OrderTrackingRequest request) {
            return base.Channel.ReceiveOrderTracking(request);
        }
        
        public System.Threading.Tasks.Task<Marfrig.Integration.Test.IntegrationService.OrderTrackingResponse> ReceiveOrderTrackingAsync(Marfrig.Integration.Test.IntegrationService.OrderTrackingRequest request) {
            return base.Channel.ReceiveOrderTrackingAsync(request);
        }
        
        public string TestMethod() {
            return base.Channel.TestMethod();
        }
        
        public System.Threading.Tasks.Task<string> TestMethodAsync() {
            return base.Channel.TestMethodAsync();
        }
    }
}
